CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(20) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(120) NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE courses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(255) NOT NULL,
    CONSTRAINT courses_pk PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE user_courses (
    user_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    CONSTRAINT user_courses_pk PRIMARY KEY (user_id, course_id),
    CONSTRAINT user_courses_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_courses_course_fk FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');

INSERT INTO users (username, email, password) VALUES ('tiger', 'user1@example.com', '$2a$12$rPYIxQrTjPvr2Cq5XZdmw../SisdEswQh5IUxPWQesnukWJXo.27e');
INSERT INTO users (username, email, password) VALUES ('ahmsalah', 'user2@example.com', '$2a$12$rPYIxQrTjPvr2Cq5XZdmw../SisdEswQh5IUxPWQesnukWJXo.27e');

INSERT INTO courses (title, description) VALUES ('Math 101', 'Basic Mathematics');
INSERT INTO courses (title, description) VALUES ('Science 101', 'Basic Science');

INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO user_roles (user_id, role_id) VALUES (2, 2);

INSERT INTO user_courses (user_id, course_id) VALUES (1, 1);
INSERT INTO user_courses (user_id, course_id) VALUES (2, 2);